containers:
  - subdomain: cv
    image: ghcr.io/lucykowal/cv:main
    name: cv
    container_port: "80"
    host_port: "8081"
  - subdomain: false
    image: ghcr.io/lucykowal/home:main
    name: blog
    container_port: "80"
    host_port: "8080"

vault_github_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30653831316432623665366161616534366661363535663136356462623039303466366433323962
  3933333865303663333530376339373938643764636261310a396161356138623330333537303930
  64663036363437633864663363303731623634323630663631333465636539313938356131323566
  3733336235653139620a613032643436393131393366376637346366333035373366366531666230
  3363

vault_github_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30336562346534393063363037616531376564353739343466323232356533393432336161616165
  3061343738666438313763356565663566663736346132350a663038386537333362346632313735
  64643365343833336337313935343665376230333464666433346466643830613462623139366365
  6466323362376561350a306537363431613061336564343234333537636632336632333163656430
  61613662396164656438316339353461363138613638363233363361353235386631646537666235
  6664663830356636646337366130633638343333346134643938

vault_certbot_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66643365326235636239336133383863303539613431343133633830616639336565623632356161
  6233353666633030326234656666633666643362653530300a316134396566386238366339396339
  65343735373762646439336665396265356263633166663466633963616532336335353065333330
  3130376132626539640a303564643362663761636266353039313866633766343930643130393732
  35326465323263643163393933333436333161396461396130373332316266636662

vault_tailscale_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66303061346531663366633062353932303132656631653065636639346533653266323633613063
  3033643762623265663035313562666337623136333135340a376366323662306133336639373636
  32376230303532663761313065626135366338666337363165323030646165303139613235616130
  3861666133333535390a616439636238303462343536383735313463396231636339616338383434
  64346334393337356434643263376432353735393639366137383335333935386631366334636131
  34373065343466383465663437643666343463646436333164373833616233393564333464303431
  373766643963333034373166306261356132
